#!/usr/bin/env bash

sudo apt install build-essential libfontconfig1 qt5-qmake qtbase5-dev openssl libssl-dev libssl1.0 libgl1-mesa-dev libqt5x11extras5


sudo apt-get install 

wget https://download.qt.io/new_archive/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run
chmod +x qt-opensource-linux-x64-5.7.0.run 
./qt-opensource-linux-x64-5.7.0.run
rm qt-opensource-linux-x64-5.7.0.run 
 
