#!/usr/bin/env bash

if [ $1 == "dev" ]; then
wget https://download.qt.io/new_archive/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run
chmod +x qt-opensource-linux-x64-5.7.0.run 
./qt-opensource-linux-x64-5.7.0.run
rm qt-opensource-linux-x64-5.7.0.run 
fi

wget https://apt.devkitpro.org/install-devkitpro-pacman
chmod +x ./install-devkitpro-pacman
sudo ./install-devkitpro-pacman

echo 1,3,11,12,14 | sudo dkp-pacman -S --noconfirm gba-dev
